spring.application.name=transactions

spring.data.mongodb.uri=mongodb://localhost:27017/test
spring.data.mongodb.auto-index-creation=true

#Intenta como maximo 10 veces
resilience4j.retry.instances.paymentProvider.max-attempts=10

#Entre intento e intento, espera 20 segundos.
resilience4j.retry.instances.paymentProvider.wait-duration=20s

#Haz Retry cuando ocurra ProviderException
#resilience4j.retry.instances.paymentProvider.retry-exceptions=com.financial.transactions.exceptions.ProviderException

#Voy a revisar el comportamiento segun cantidad de llamadas
resilience4j.circuitbreaker.instances.paymentProvider.sliding-window-type=COUNT_BASED

#Voy a observar las ultimas 5 llamadas
resilience4j.circuitbreaker.instances.paymentProvider.sliding-window-size=5

#Necesito al menos 5 llamadas antes de decidir si abro el circuito.
resilience4j.circuitbreaker.instances.paymentProvider.minimum-number-of-calls=5

#Si el porcentaje de errores llega al 50%, puedo abrir el circuito.
resilience4j.circuitbreaker.instances.paymentProvider.failure-rate-threshold=50

#Cuando abra el circuito, espera 10 segundos antes de comprobar si el proveedor ya funciona.
resilience4j.circuitbreaker.instances.paymentProvider.wait-duration-in-open-state=10s

#Despues de esos 10 segundos, deja pasar 2 llamadas de prueba.
resilience4j.circuitbreaker.instances.paymentProvider.permitted-number-of-calls-in-half-open-state=2

#Cuando ocurra ProviderException, cuentalo como un fallo para el Circuit Breaker.
resilience4j.circuitbreaker.instances.paymentProvider.record-exceptions=com.financial.transactions.exceptions.ProviderException

logging.level.io.github.resilience4j.circuitbreaker=DEBUG

logging.level.io.github.resilience4j.retry=DEBUG

security.api-key=${API_KEY:ApiKeyExam}

provider.api-key=${PROVIDER_API_KEY:dev-provider-key}

provider.base-url=http://localhost:8081

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=transactions-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

